package de.lemo.apps.entities;

public enum Features {
	LINKCOUNT,
	WORDCOUNT,
	ANSWERCOUNT,
	IMAGECOUNT,
	UPVOTES,
	DOWNVOTES,
	COMMENTCOUNT,
	POSTCOUNT,
	POST_RATING_MAX,
	POST_RATING_MIN,
	POST_RATING_SUM,
	RECEIVED_UPVOTES,
	RECEIVED_DOWNVOTES,
	UNIT_PROGRESS,
	LESSON_PROGRESS,
	PROGRESS_PERCENTAGE
}
